### ISSUE TITLE
Tools take several minutes to run

### ISSUE THREAD

**Issue by inlined** [cloudevents/spec#241] opened 2018-06-20 19:35 UTC
I love that we have easy portable checkers, but it's annoying that these shell scripts take several minutes to run.

Is there a better option? We could look for inefficiencies in the script or rewrite them in a language which we agree is an acceptable dependency.

**Comment by duglin** [comment] 2018-06-20 20:02
I'd love to rewrite them in golang so we can have a stand-alone executable and while in there "do it right" by having a real md parser because I feel like the current stuff is more of a hack/guesses than anything else.  I haven't confirmed this, but I think the longest time is the href checker which needs to hit the internet *a lot*, and we're dependent on the speed of other sites.  There is an option to skip checking external sites (and just check local hrefs), so we could turn that on but TBH it makes me nervous to skip - even if we just skipped it for PRs and left it on for master because then when things are bad we'd need a 2nd PR to fix the first PR.

**Comment by inlined** [comment] 2018-06-20 20:04
Well, even if we leave on the external MD checker, a parallel parser w/ an aggregator can speed this up massively.

**Comment by moderation** [comment] 2018-06-29 02:15
For code the hits the internet _a lot_ Golang is ideal. Using goroutines this could be parallelized. Can you provide a link to the checkers in question and I'll take a look?

**Comment by duglin** [comment] 2018-06-29 02:17
@moderation see: https://github.com/duglin/vlinker  but its in bash :-)

**Comment by duglin** [comment] 2021-07-01 02:00
I"m going to suggest that we close this - does anyone have any concern about this?

**Comment by jskeet** [comment] 2021-07-02 08:08
It's not even clear to me what checkers we're talking about here, but if it hasn't been painful enough to cause additional comments in the last 3 years, I think it's fine to close :)

**Closed** 2021-07-05 13:31 UTC
Labels: not-required-for-v1.0
