### ISSUE TITLE
Deserialization of CloudEvent from Azure Service Bus

### ISSUE THREAD

**Issue by snesbitt76** [cloudevents/spec#555] opened 2020-01-03 01:29 UTC
Hello,

I have published a CloudEvent 1.0 to an Azure Service Bus queue. 

To read this event from the Azure Service Bus queue, I have an Azure Function v2.0 with a ServiceBusTrigger.

Based on this [doco](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus#trigger---usage), a v2.0 Azure Function binds to a service bus message via the Microsoft.Azure.ServiceBus.Message type.

So to get the original CloudEvent object, I need to deserialize the [message.Body](https://docs.microsoft.com/en-au/dotnet/api/microsoft.azure.servicebus.message.body?view=azure-dotnet#Microsoft_Azure_ServiceBus_Message_Body) byte array.

`messageBody = Encoding.UTF8.GetString(message.Body, 0, message.Body.Length);`
`cloudEvent = JsonConvert.DeserializeObject<CloudEvent>(messageBody);`

I have confirmed the messageBody string is a JSON serialized representation of the CloudEvent object.

However, when I attempt to deserialise with JsonConvert.DeserializeObject<CloudEvent> I get the following runtime error:

> Unable to find a constructor to use for type CloudNative.CloudEvents.CloudEvent. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. 
 
I'm new to CloudEvents so I think I'm just missing something basic here, but I can't find any serialization methods or extensions to help with this scenario. 

Any guidance will be greatly appreciated.

**Comment by duglin** [comment] 2020-01-06 13:52
@clemensv perhaps you know of someone who might be able to help?

**Comment by clemensv** [comment] 2020-01-14 15:57
This issue should be in the sdk-csharp repo. 

The problem here is that the CloudEvents class isn't meant to be used for POCO deserialization with JSON.NET. Turning a message payload into a CloudEvent is done with the ICloudEventFormatter abstraction and, here, with JsonEventFormatter since CloudEvents supports different formats and there is no uniform serialization abstraction in .NET Core that would work for that.

This by design, but probably woth a not in the doc. I hope the answer helps.

**Comment by duglin** [comment] 2020-01-23 15:36
@snesbitt76 I'm going to close this per @clemensv's suggestion. If you think we need to reopen it please let me know

**Closed by duglin** 2020-01-23 15:36 UTC
