### ISSUE TITLE
Proposal to form a sub-working group for a schema registry API

### ISSUE THREAD

**Issue by clemensv** [cloudevents/spec#610] opened 2020-04-29 13:28 UTC
Microsoft proposes the formation of a sub-working group to starts working on a common schema registry API interface in parallel with the ongoing efforts.

The schema registry API should, in our view, fulfill the following minimal requirements:
- Provide a management and retrieval interface over HTTP (AMQP services can leverage the [HTTP-over-AMQP](https://www.oasis-open.org/committees/document.php?document_id=65571&wg_abbrev=amqp) binding that is pending in the AMQP TC)
-  Allow for storing schema file streams for any data serialization format for both schema-driven serialization and data validation, e.g. Avro or Protobuf or XML or JSON schemas. 
- Allow for storing for multiple versions for each schema.
- Allow for storing of logical groups of such schemas. 

Our concrete initial proposal is to create a very simple REST API for this purpose, that manages a resource graph like this:

https://example.com/**schemagroups**/{schemagroup}/**schemas**/{schema}/**versions**/{version}

- "schemagroups" collection: the top level collection of schema groups. Each group is a logically related set of schemas, typically belonging to a particular application or subject to shared access control rules.
- "schemas" collection: the collection of schemas belonging to a schema group. 
- "versions": the versions of schema documents belonging to a particular schema.

The version identifiers, eg. `.../versions/4` are assigned and managed by the service and do not necessarily reflect the developer-assigned version number. A service implementation MAY enforce certain dependencies between versions. For instance, a service implementation that specifically understand Avro schemas might be configured such that a new schema version can only be added if it satisfies certain backwards compatibility criteria. If the added schema does not satisfy those criteria, the service might then report a conflict (409).  

In the "versions" collection, clients can add new schemas with POST against the collection root. The response is either 201 (Created) with a `Location` header that indicates the newly created schema version location, 400 (Bad Request) for a malformed request, 409 (Conflict) for a consistency violation as just discussed, or some other 5xx or 4xx response appropriate for the error condition.

Schema version can be deleted but not replaced, meaning there is no update.

The "versions" collection allows enumerating all versions of a schema with GET. The result is a JSON array holding URI-references to to the schema version documents. Schema version documents can be deleted with DELET on their schema version URI.

In the "schemas" collection clients can add new schemas by name using the PUT method with the schema name in the URI segment. This creates a new version collection for the schema if required and then appends the schema as the latest version. A GET against ".../schemas/{schema}" will return the latest version of the schema document stored in the schema collection. 

A schema version collection including all stored schemas is deleted with a DELETE on ".../schemas/{schema}".

The management of schema groups is equivalently straightforward. A PUT on "/schemagroups/{schemagroup}" with the group name in the segment creates the group. A DELETE deletes it. 

Authorization is done using existing HTTP mechanisms, e.g. OAuth Bearer tokens.

**Comment by fmvilas** [comment] 2020-04-30 16:50
This is interesting. Let's work on this together with the AsyncAPI community too 👍

**Comment by clemensv** [comment] 2020-05-04 14:01
@fmvilas Absolutely. It's a thing everyone needs.

**Comment by mikehelmick** [comment] 2020-05-06 15:47
The `dataschemacontent` field in the discovery API was intended to also serve as a schema registry

https://github.com/cloudevents/spec/blob/master/discovery.md#dataschemacontent

**Comment by n3wscott** [comment] 2020-05-06 16:30
I would love something that let's us understand the full event shape including known extensions that producers will use for an event envelope, which is a blindspot that dataschema has.

**Comment by deissnerk** [comment] 2020-05-06 16:49
@n3wscott I would love that, too, but I think it's not the intention of this proposal. We could probably evolve the discovery API to provide this kind of information. In addition to a discovery API, we may need a catalog format that a producer can use to register with some middleware and describe all the events it produces. 
A catalog could also be used to generate documentation (Javadoc for CloudEvents 😄 ) or source code. 
Nevertheless, a schema registry can be an important piece in the puzzle. So far, most people do not really know what to do with the `dataschema` attribute.

**Comment by clemensv** [comment] 2020-05-08 08:02
A "pure" schema registry will be useful in contexts beyond CloudEvents, which is increases the likelihood of broad adoption, which will then again benefit CloudEvents. 

I strongly prefer keeping the schema registry separate from discovery, which ought to be about finding subscription endpoints based on criteria related to the event metadata. I consider that orthogonal to concerns of payload encoding, which schema registries are commonly used for.

**Comment by deissnerk** [comment] 2020-05-08 08:24
@clemensv I agree completely. 
Reading my previous statement again, I realized that it might be misleading regarding this point. Working on discovery as I proposed, would complement a schema registry, not replace it.

**Comment by ryanhorn** [comment] 2020-05-08 18:07
Agree, they should be decoupled, but would still be complementary. Would love to participate in this as well.

**Comment by grant** [comment] 2020-05-09 00:04
I am in agreement with the general proposal.
What are the logistical steps needed in order to proceed or see a more concrete proposal?

**Comment by duglin** [comment] 2020-05-09 22:38
This was approved on the 5/7 call. I'll work with @clemensv off-line on the next steps in the process

**Comment by EricWittmann** [comment] 2020-05-15 13:51
It would be great to collaborate in this area!  At Red Hat we have a new [Schema/API Registry](https://github.com/Apicurio/apicurio-registry) and it would be smart to align with what's going on in this community as well.  Looking forward to hearing about next steps.

**Comment by duglin** [comment] 2021-07-15 03:20
I'm going to propose that we close this since we're working on it in the main WG.
@clemensv  - thoughts?

**Comment by erikerikson** [comment] 2021-07-22 23:42
This seems bypassed by actions.  I support closing it.

**Closed** 2021-07-28 13:23 UTC
