### ISSUE TITLE
Introduction to OpenAgenda

### ISSUE THREAD

**Issue by romainlange** [cloudevents/spec#130] opened 2018-03-27 14:47 UTC
Hi,

sorry for using an issue ticket as an introduction.
We are based in Paris, France, and develop OpenAgenda.com , a platform helping to make inventories of events and to publish it as Open Data, under Open License, following schema.org/Events standard.

Here is an example with the calendar of the city of Montreuil, neighbour of Paris : https://openagenda.com/montreuil

We have an API and we are available if we can help.

Best regards.

**Comment by SeanFeldman** [comment] 2018-03-27 18:39
Frankly, I like this approach.
1. It's trackable. Slack conversations get overwhelming.
2. You get confirmation registration is completed when the issue is closed.
👍

**Comment by duglin** [comment] 2018-03-27 18:47
I'm slow, I admit it :-)
- If this is an ad then I don't think this is appropriate. You can talk to the CNCF org team if you want to suggest an alternative mechanism for us to track meetings, events, issues, etc... but we're following the guidance/pattern they use
- If you are saying that you guys produce events and are interested in helping to shape our specification by including your usecases, making suggested changes... then that's great. Please see our README for information on how to join the fun.

Either way I think we can close this issue but reopen if it I'm mistaken.

**Closed by duglin** 2018-03-27 18:47 UTC

**Comment by SeanFeldman** [comment] 2018-03-27 18:57
I've assumed it was intro to join the WG @duglin.

**Comment by romainlange** [comment] 2018-03-28 07:46
Yes it was ;)
I check the README.

**Comment by duglin** [comment] 2018-03-28 09:45
@romainlange cool!  In that case welcome! And we'd love to have your input! In particular, I personally would like to get your input on the PRs that involve adding some additional attributes that people think would be useful - see this: https://github.com/cloudevents/spec/pull/128#issuecomment-376724482

**Comment by SeanFeldman** [comment] 2018-03-28 19:29
Moral: always assume the best in humans, unless proven otherwise 😃

**Comment by leecalcote** [comment] 2018-03-28 21:27
I would’ve responded the same way as @duglin.
